version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: streaming
  subscriptions:
    container_name: subscriptions
    image: mu2729/streaming-subscriptions
    ports:
      - 8082:8082 # slightly bruh.
    env_file:
      - subscriptions.env
    depends_on:
      - postgres
      - etcd
  catalogs:
    container_name: catalogs
    image: mu2729/streaming-catalogs
    ports:
      - 8081:8081
    env_file:
      - catalogs.env
    depends_on:
      - postgres
      - etcd
  etcd:
    image: quay.io/coreos/etcd:latest
    ports:
    - "2379:2379"
    command: >-
      /usr/local/bin/etcd
      -name node1
      -advertise-client-urls http://etcd:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://etcd:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster node1=http://etcd:2380
      -cors="*"
