version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - ${DB0_PORT}:5432
    environment:
      POSTGRES_USER: ${DB0_USER}
      POSTGRES_PASSWORD: ${DB0_PASSWORD}
      POSTGRES_DB: ${STREAMING_DB}
  uploader-db:
      container_name: uploader-db
      image: postgres
      ports:
        - ${UDB_PORT}:5432
      environment:
        POSTGRES_USER: ${UDB_USER}
        POSTGRES_PASSWORD: ${UDB_PASSWORD}
        POSTGRES_DB: ${STREAMING_DB}
  subscriptions:
    container_name: subscriptions
    image: mu2729/streaming-subscriptions
    ports:
      - ${SUBSCRIPTIONS_PORT}:8080
    environment:
      KUMULUZEE_ENV_NAME: ${ENVIRONMENT}
      KUMULUZEE_DATASOURCES0_CONNECTION-URL: jdbc:postgresql://${HOST}:${DB0_PORT}/${SUBSCRIPTIONS_DB}
      KUMULUZEE_DATASOURCES0_USERNAME: ${DB0_USER}
      KUMULUZEE_DATASOURCES0_PASSWORD: ${DB0_PASSWORD}
      KUMULUZEE_SERVER_BASE-URL: http://${HOST}:${SUBSCRIPTIONS_PORT}
      KUMULUZEE_SERVER_HTTP_PORT: 8080
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://${HOST}:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://${HOST}:2379
    depends_on:
      - postgres
      - etcd
  catalogs:
    container_name: catalogs
    image: mu2729/streaming-catalogs
    ports:
      - ${CATALOGS_PORT}:8080
    environment:
      KUMULUZEE_ENV_NAME: ${ENVIRONMENT}
      KUMULUZEE_DATASOURCES0_CONNECTION-URL: jdbc:postgresql://${HOST}:${DB0_PORT}/${STREAMING_DB}
      KUMULUZEE_DATASOURCES0_USERNAME: ${DB0_USER}
      KUMULUZEE_DATASOURCES0_PASSWORD: ${DB0_PASSWORD}
      KUMULUZEE_SERVER_BASE-URL: http://${HOST}:${CATALOGS_PORT}
      KUMULUZEE_SERVER_HTTP_PORT: 8080
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://${HOST}:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://${HOST}:2379
    depends_on:
      - postgres
      - etcd
  recommendations:
    container_name: recommendations
    image: mu2729/streaming-recommendations
    ports:
    - ${RECOMMENDATIONS_PORT}:8080
    environment:
      KUMULUZEE_ENV_NAME: ${ENVIRONMENT}
      KUMULUZEE_SERVER_BASE-URL: http://${HOST}:${RECOMMENDATIONS_PORT}
      KUMULUZEE_SERVER_HTTP_PORT: 8080
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://${HOST}:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://${HOST}:2379
    depends_on:
    - etcd
  statistics:
    container_name: statistics
    image: mu2729/streaming-statistics
    ports:
    - ${STATISTICS_PORT}:8080
    environment:
      KUMULUZEE_ENV_NAME: ${ENVIRONMENT}
      KUMULUZEE_SERVER_BASE-URL: http://${HOST}:${STATISTICS_PORT}
      KUMULUZEE_SERVER_HTTP_PORT: 8080
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://${HOST}:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://${HOST}:2379
    depends_on:
    - etcd
  subscriptions:
    container_name: uploader
    image: mu2729/streaming-uploader
    ports:
      - ${UPLOADER_PORT}:8080
    environment:
      KUMULUZEE_ENV_NAME: ${ENVIRONMENT}
      KUMULUZEE_DATASOURCES0_CONNECTION-URL: jdbc:postgresql://${HOST}:${UDB_PORT}/${STREAMING_DB}
      KUMULUZEE_DATASOURCES0_USERNAME: ${UDB_USER}
      KUMULUZEE_DATASOURCES0_PASSWORD: ${UDB_PASSWORD}
      KUMULUZEE_SERVER_BASE-URL: http://${HOST}:${UPLOADER_PORT}
      KUMULUZEE_SERVER_HTTP_PORT: 8080
      KUMULUZEE_CONFIG_ETCD_HOSTS: http://${HOST}:2379
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://${HOST}:2379
      SERVICE_OS: linux
      SERVICE_FILES_PATH: /files/
    depends_on:
      - uploader-db
      - etcd

  etcd:
    image: quay.io/coreos/etcd:latest
    container_name: etcd
    ports:
    - "2379:2379"
    command: >-
      /usr/local/bin/etcd
      -name node1
      -advertise-client-urls http://etcd:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://etcd:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster node1=http://etcd:2380
      -cors="*"
