apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogs
  template:
    metadata:
      labels:
        app: catalogs
    spec:
      containers:
      - image: mu2729/streaming-catalogs
        name: catalogs
        env:
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_SERVER_HTTP_PORT
          value: "8080"
        - name: KUMULUZEE_SERVER_BASE-URL
          value: http://159.122.186.127:30836
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://postgres:5432/streaming
        - name: KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL
          value: http://etcd:2379/health
        ports:
        - containerPort: 8080
          protocol: TCP
          name: catalogs-port
        livenessProbe:
          httpGet:
            path: /health
            port: catalogs-port
          initialDelaySeconds: 30
          periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: catalogs
spec:
  type: NodePort
  selector:
      app: catalogs
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080